### PR TITLE
Fixes ctrl+enter to save bundle

### LINKED ISSUE #1521: Bundle run screen: Ctrl + Enter should run a bundle

### PR DESCRIPTION
**Pull request by epicfaace**
Fixes #1521. This error happens on the bundle run
screen. The fix makes sure that the `onKeyPress`
prop is passed on and uses the right key code
(13) for enter.

### CODE REVIEW

File: frontend/src/components/worksheets/NewRun/NewRun.jsx [hunk 1]
```diff
@@ -491,7 +491,7 @@ class NewRun extends React.Component<{
                     placeholder="python train.py --data mydataset.txt"
                     maxRows={4}
                     onKeyDown={(e) => {
-                         if(e.keyCode == 18 && (e.ctrlKey || e.shiftKey || e.metaKey)) {
+                         if(e.keyCode === 13 && (e.ctrlKey || e.shiftKey || e.metaKey)) {
```
Comment (yipenghe) [inline frontend/src/components/worksheets/NewRun/NewRun.jsx:494]: some time we should get all these == to ===, so many warnings lol

**Review by yipenghe — APPROVED** [review]
Ctrl+enter works after checking out to this branch
