### PR TITLE
Fix jQuery invalid selector bug for the search bar

### LINKED ISSUE #3403: Invalid selector error occurred when using search bar on the profile page
**Describe the bug**
Only occurred at localhost.
Screen Shot 2021-04-15 at 9 22 25 PM

**To Reproduce**
Steps to reproduce the behavior :
1. Go to MY PROFILE page
2. Click on the search bar
3. See error

### PR DESCRIPTION
**Pull request by yuqijin**
### Reasons for making this change

Add check of whether the worksheet terminal exists on the current page

### Related issues

fixes #3403 

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

File: frontend/src/components/NavBar.js [hunk 1]
```diff
@@ -204,14 +204,16 @@ class NavBar extends React.Component<{
...
         // Disable the terminal to avoid the search bar text being mirrored in the terminal
-        if (
-            $('#command_line')
-                .terminal()
-                .enabled()
-        ) {
-            $('#command_line')
-                .terminal()
-                .focus(false);
+        if ($('#command_line').length > 0) {
```
Comment (epicfaace) [inline frontend/src/components/NavBar.js]: Let's add `const $cmd = $('#command_line');` at the beginning and rewrite the code in terms of `$cmd` to make this code cleaner.

**Review by epicfaace — APPROVED** [review]
