### PR TITLE
Fix the bug of "Save" Button for worksheet not working

### LINKED ISSUE #3007: Save button does not work when the user edits the source for a worksheet
**Describe the bug**
image

**To Reproduce**
Steps to reproduce the behavior :
1. Click on 'edit source'
2. Make some changes
4. Click on 'save'

### PR DESCRIPTION
**Pull request by yuqijin**
### Reasons for making this change

The save button did not work. The reason is `setState` is an async function. We should first ensure the frontend state has already been updated properly before we make requests to the backend.

### Related issues

fixes #3007 

### Screenshots

ezgif com-gif-maker

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

**Review by epicfaace — APPROVED** [review]

File: frontend/src/components/worksheets/Worksheet/Worksheet.js [hunk 1]
```diff
@@ -1120,25 +1120,30 @@ class Worksheet extends React.Component {
...
                 var editor = ace.edit('worksheet-editor');
                 if (saveChanges) {
-                    this.setState({
-                        ws: {
-                            ...this.state.ws,
-                            info: {
-                                ...this.state.ws.info,
-                                source: editor.getValue().split('\n'),
+                    // Use callback function to ensure the worksheet info will not be sent to the backend until the frontend state has finished updating
+                    this.setState(
```
Comment (epicfaace) [inline frontend/src/components/worksheets/Worksheet/Worksheet.js:1125]: Actually, can we wrap this in a promise and then use `await` instead? Given that we want to refactor callbacks into promises anyway

**Review by epicfaace — CHANGES_REQUESTED** [review]

File: frontend/src/components/worksheets/Worksheet/Worksheet.js (hunk 1 above)
Comment (yuqijin) [reply frontend/src/components/worksheets/Worksheet/Worksheet.js:1125]: Actually for setState, I do not think we should wrap it into a promise and use await since it already provides a callback to take actions when setState is completed

Comment (epicfaace) [reply frontend/src/components/worksheets/Worksheet/Worksheet.js:1125]: What's the drawback of wrapping it in a promise and using await? It seems like it would make the code look at a bit cleaner, related to @Levilian 's work of changing callbacks -> promises?

something like this:

```
await new Promise(e => this.setState({...}, e));
```

If there's a drawback in doing it this way, we can keep using the callbacks, though.

Comment (yuqijin) [reply frontend/src/components/worksheets/Worksheet/Worksheet.js:1125]: I updated the PR to use `promise` instead since you mentioned in the offline discussion that we have a code style convention of using `promise` instead.

File: frontend/src/components/worksheets/Worksheet/Worksheet.js [hunk 2]
```diff
@@ -1121,26 +1121,30 @@ class Worksheet extends React.Component {
             if (this.hasEditPermission()) {
                 var editor = ace.edit('worksheet-editor');
                 if (saveChanges) {
-                    this.setState({
+                    // Use promise here to ensure the worksheet info will not be sent to the backend until the frontend state has finished updating
+                    const setAsyncState = (newState) =>
+                        new Promise((resolve) => this.setState(newState, resolve));
+                    setAsyncState({
```
Comment (epicfaace) [inline frontend/src/components/worksheets/Worksheet/Worksheet.js]: We could just do this instead (using `async` / `await` instead of callbacks):

```
await new Promise(e => this.setState({
                        ws: {
                            ...this.state.ws,
                            info: {
                                ...this.state.ws.info,
                                source: editor.getValue().split('\n'),
                            },
                        },
                    }, e));
```

**Review by epicfaace — APPROVED** [review]

**Review by epicfaace — APPROVED** [review]
