### PR TITLE
Refresh worksheet when metadata is changed in bundle side panel

### LINKED ISSUE #211: Refresh doesn't work properly
With the new change to automatic refresh (v0.1.11), refreshing is broken:
- If one edits the metadata in the side panel, this doesn't get automatically updated in the table.
- Right clicking on 'Remove bundle' doesn't cause the page to refresh and show everything else except what's been deleted.
- When edit the source (even when it's as simple as inserting new markdown) and click save, then refreshing doesn't work.

### PR DESCRIPTION
**Pull request by ChengshuLi**
fix #211 first bug
@percyliang

### CODE REVIEW

File: codalab/apps/web/static/js/bundle/bundle_interface.jsx [hunk 1]
```diff
@@ -43,13 +46,17 @@ var Bundle = React.createClass({
             ref={'file_browser'}
           />);
         }
-
+        var bundleMetadataChanged = this.refreshBundle
+        if (this.props.bundle_uuid) {
+          // if it is the bundle detail side panel, it should call refreshWorksheet
+          bundleMetadataChanged = this.props.bundleMetadataChanged
+        }
```
Comment (yashsavani) [inline codalab/apps/web/static/js/bundle/bundle_interface.jsx]: I prefer to use `var bundleMetadataChanged = this.props.bundle_uuid? this.props.bundleMetadataChanged : this.refreshBundle`

File: codalab/apps/web/static/js/worksheet/worksheet_interface.jsx [hunk 2]
```diff
@@ -285,6 +274,77 @@ var Worksheet = React.createClass({
         }
     },
 
+    // updateRunBundles fetch all the "unfinished" bundles in the worksheet, and recursively call itself until all the bundles in the worksheet are finished.
+    updateRunBundles: function(worksheetUuid, numTrials, updatingBundleUuids) {
+      var bundleUuids = updatingBundleUuids ? updatingBundleUuids : this.state.updatingBundleUuids;
+      var startTime = new Date().getTime();
+      var self = this;
```
Comment (yashsavani) [inline codalab/apps/web/static/js/worksheet/worksheet_interface.jsx]: Try to use `bind(this)` instead of `var self = this`

**Comment by ChengshuLi** [comment]
Fixed three bugs
1) change metadata in bundle side panel will refresh worksheet 
2) when you add new elements (either schema or markup) in the edit mode and click save, focus will be set on that new element. It's mistakenly implemented before.
3) fix bundle refresh, put the state "updatingBundleUuds" and "isUpdatingBundle" to worksheet_interface.js rather than worksheet_items.js because worksheet_items is teared down and re-mounted every time we switch between edit mode and view mode
