### PR TITLE
Control modal entirely with react props

### LINKED ISSUE #1670: [New frontend] Shortcut '?' is broken
The shortcut '?' is broken saying
`TypeError: jquery__WEBPACK_IMPORTED_MODULE_8___default(...)(...).modal is not a function
`
_Originally posted by @yipenghe in https://github.com/codalab/codalab-worksheets/pull/1653_

### PR DESCRIPTION
**Pull request by epicfaace**
Removing jquery from one more place! Fixes #1670

### CODE REVIEW

File: frontend/src/components/worksheets/ExtraWorksheetHTML/ExtraWorksheetHTML.js [hunk 1]
```diff
@@ -1,152 +1,148 @@
...
+                    </tr>
+                </tbody>
+            </table>
+        </Modal.Body>
+    </Modal>);
+
+let ExtraWorksheetHTML = ({ showGlossaryModal, toggleGlossaryModal }) => (
     <React.Fragment>
-        <div id='save_progress' className='progress-message'>
-            <img src='/img/Preloader_Small.gif' /> Saving...
```
Comment (epicfaace) [inline frontend/src/components/worksheets/ExtraWorksheetHTML/ExtraWorksheetHTML.js:7]: removed this because it wasn't used anywhere else in the codebase

**Review by yipenghe — APPROVED** [review]
Cool

File: frontend/src/components/worksheets/Worksheet/Worksheet.js [hunk 2]
```diff
@@ -642,14 +645,14 @@ class Worksheet extends React.Component {
                 );
             }
         }
-        Mousetrap.bind(['?'], function(e) {
-            $('#glossaryModal').modal('show');
+        // Below are allowed shortcut even when a dialog is opened===================
```
Comment (epicfaace) [inline frontend/src/components/worksheets/Worksheet/Worksheet.js]:
```suggestion

```
