### PR TITLE
Fix Scrolling Issue

### LINKED ISSUE #3556: Scrolling Issue on the Frontend
~~When you are viewing a worksheet in a window that's narrow, if you press shift-G to go to the end of the worksheet, it doesn't seem to scroll all the way down.~~
~~And sometimes it scrolls too far down.~~
extra scrollbar on the right in the tables in a worksheet
extra scrollbar on the page when the window is narrow

### PR DESCRIPTION
**Pull request by yuqijin**
### Reasons for making this change

remove extra scrolling bar

### Related issues

fixes #3556 

### Screenshots

image

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

**Review by epicfaace — APPROVED** [review]
Looks good. I think we should remove the "fixes https://github.com/codalab/codalab-worksheets/issues/3556" wording because this only fixes part of that issue, but not the Ctrl+G issue.

File: frontend/src/components/worksheets/items/TableItem/TableItem.js [hunk 1]
```diff
@@ -261,8 +261,9 @@ class TableItem extends React.Component<{
         });
         return (
             <div className='ws-item'>
-                <TableContainer style={{ overflowX: 'auto' }}>
-                    <Table className={tableClassName} style={{ marginBottom: '0' }}>
+                <TableContainer style={{ overflowX: 'auto', overflowY: 'hidden' }}>
+                    {/*The 0.5px margin space is for the divider between table header and table body*/}
```
Comment (epicfaace) [inline frontend/src/components/worksheets/items/TableItem/TableItem.js]: I don't think we need this comment here, it seems too trivial to need a comment

**Comment by yuqijin** [comment]
> Looks good. I think we should remove the "fixes #3556" wording because this only fixes part of that issue, but not the Ctrl+G issue.

The remaining issue is the redundant scrolling bar when the window is narrow. The latest commit fix it.

File: frontend/src/components/worksheets/Worksheet/WorksheetHeader.js [hunk 2]
```diff
@@ -46,7 +46,7 @@ export default ({
     toggleWorksheetSize,
     showBundleContent,
 }) => (
-    <Sticky top={6} innerZ={1059}>
+    <Sticky top='#codalab-app-bar' innerZ={1059}>
```
Comment (epicfaace) [inline frontend/src/components/worksheets/Worksheet/WorksheetHeader.js:49]: Can we actually factor out "codalab-app-bar" into a constant in constants.js? so that we don't actually refactor the header component and remove the id and make this break again

**Review by epicfaace — APPROVED** [review]

File: frontend/src/components/worksheets/Worksheet/WorksheetHeader.js (hunk 2 above)
Comment (epicfaace) [reply frontend/src/components/worksheets/Worksheet/WorksheetHeader.js:49]: Let's do this later
