### PR TITLE
Fix JSON Display

### LINKED ISSUE #4037: Screen goes blank when looking at a JSON bundle
To reproduce, visit this page:

https://codalab.stanford.edu/bundles/0x6e3abaeb28e34640a12a9a66d27d8ddf

### PR DESCRIPTION
**Pull request by jzwang43**
### Reasons for making this change

Bundle detail screen goes blank sometimes if the file is JSON.

### Related issues

Fixes #4037 

### Screenshots

image

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

File: frontend/src/components/Bundle/Bundle.js [hunk 1]
```diff
@@ -102,7 +102,12 @@ class Bundle extends React.Component<
             if (!info) return;
             if (info.type === 'file' || info.type === 'link') {
                 return fetchFileSummary(this.props.uuid, '/').then((blob) => {
-                    this.setState({ fileContents: blob, stdout: null, stderr: null });
+                    this.setState({
+                        fileContents:
```
Comment (epicfaace) [inline frontend/src/components/Bundle/Bundle.js]: I think the cleanest way to do this would be to pass in `responseType: 'text'` when we call `get` from axios in the first place -- then it won't parse as json in the first place.

**Review by epicfaace — CHANGES_REQUESTED** [review]

File: frontend/src/components/Bundle/Bundle.js (hunk 1 above)
Comment (jzwang43) [reply frontend/src/components/Bundle/Bundle.js]: Hi, Ashwin thanks for the suggestion. Just applied.

File: frontend/src/util/apiWrapper.js [hunk 2]
```diff
@@ -129,7 +130,14 @@ export const fetchFileSummary = (uuid, path) => {
     };
     const url =
         '/rest/bundles/' + uuid + '/contents/blob' + path + '?' + new URLSearchParams(params);
-    return get(url, { headers: { Accept: 'text/plain' } });
+    return get(
+        url,
+        {
+            headers: { Accept: 'text/plain' },
+        },
+        // need to define transformResponse to prevent json being parsed due to the issue discussed in: https://github.com/axios/axios/issues/811
```
Comment (epicfaace) [inline frontend/src/util/apiWrapper.js]:
```suggestion
        // Get the raw text response and don't parse JSON. Need to define transformResponse to prevent JSON being parsed due to the issue discussed in: https://github.com/axios/axios/issues/811
```

File: frontend/src/util/apiWrapper.js [hunk 3]
```diff
@@ -2,9 +2,10 @@ import { Semaphore } from 'await-semaphore';
 import axios from 'axios';
 import { createDefaultBundleName, pathIsArchive, getArchiveExt } from './worksheet_utils';
 
-export const get = (url, params) => {
+export const get = (url, params, options) => {
```
Comment (epicfaace) [inline frontend/src/util/apiWrapper.js]:
```suggestion
export const get = (url, params, options={}) => {
```

**Review by epicfaace — APPROVED** [review]

File: frontend/src/util/apiWrapper.js (hunk 3 above)
Comment (jzwang43) [reply frontend/src/util/apiWrapper.js]: @epicfaace is this needed? the spread operator is capable of handling undefined i think

Comment (epicfaace) [reply frontend/src/util/apiWrapper.js]: Not needed, but it would make it clearer that this argument is optional if someone reads the function definition.

**Review by epicfaace — APPROVED** [review]
