### PR TITLE
Fix login process doesn't remember the worksheets page

### LINKED ISSUE #3892: login process doesn't remember the worksheets page
To reproduce:

1. Log out.
2. Go to a worksheet page.
3. Log in.

CodaLab should take us back to the same worksheets page, but it forgets and takes us back to the user's home page instead.

### PR DESCRIPTION
**Pull request by jzwang43**
### Reasons for making this change

Currently, logging out and back in doesn't bring the user back to the previous worksheet page.

### Related issues

fixes #3892 

### Screenshots

To fix this, we just need to path in the correct props to the login page.

a

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

**Review by epicfaace — APPROVED** [review]

File: frontend/src/components/NavBar.js [hunk 1]
```diff
@@ -359,7 +359,12 @@ class NavBar extends React.Component<{
                                 <Link to='/account/signup'>
                                     <Button color='inherit'>Sign Up</Button>
                                 </Link>
-                                <Link to='/account/login'>
+                                <Link
```
Comment (epicfaace) [inline frontend/src/components/NavBar.js:362]: Should we do the same for the sign up button?

**Review by epicfaace — APPROVED** [review]

File: frontend/src/components/NavBar.js (hunk 1 above)
Comment (jzwang43) [reply frontend/src/components/NavBar.js:362]: I think it's outside the scope of this issue. But we can talk about it in the meeting? Thanks!
