### PR TITLE
Fix 'j  k' keyboard shortcut for scroll up and down

### LINKED ISSUE #2873: scrolling using keyboard shortcuts is
When you hit 'j' or 'k' to scroll down/up on a long worksheet, the worksheet scrolls with each key press, which leads to jerky behavior.  The desired behavior (as it was before) is to scroll only when the selected bundle cursor is near the edge and scroll a more significant amount so that scrolling happens less frequently.

### PR DESCRIPTION
**Pull request by yuqijin**
### Reasons for making this change
To provide the desired behavior of scrolling only when the selected bundle cursor is near the edge and scroll a more significant amount so that scrolling happens less frequently. So now, first check whether an element is visible or not, then scroll.

Ref: https://stackoverflow.com/questions/487073/how-to-check-if-element-is-visible-after-scrolling

### Related issues

fixes: #2873 

### Screenshots

Homepage:
2873-homescroll

Regular Worksheet:

2873-tablescroll

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

File: frontend/src/components/worksheets/Worksheet/Worksheet.js [hunk 1]
```diff
@@ -598,6 +598,33 @@ class Worksheet extends React.Component {
...
+        // Make the judgement only if the shouldScroll parameter has the default value of `True`
+        // Logic: Only scroll when the target element is completely not on the screen
+        if (shouldScroll) {
+            const element = subIndex
+                ? $(`#codalab-worksheet-item-${index}-subitem-${subIndex}`)
+                : $(`#codalab-worksheet-item-${index}`);
+
+            function isOnScreen(element) {
+                if (element.offset() === undefined) return false;
+                var elementOffsetTop = element.offset().top;
```
Comment (yipenghe) [inline frontend/src/components/worksheets/Worksheet/Worksheet.js]: let's use `let` instead of `var`

File: frontend/src/components/worksheets/Worksheet/Worksheet.js [hunk 2]
```diff
@@ -598,6 +598,33 @@ class Worksheet extends React.Component {
             return;
         }
         const item = this.refs.list.refs['item' + index];
+
+        // Make the judgement only if the shouldScroll parameter has the default value of `True`
+        // Logic: Only scroll when the target element is completely not on the screen
```
Comment (epicfaace) [inline frontend/src/components/worksheets/Worksheet/Worksheet.js]: Can you mention a bit more in the comment about what purpose this serves? (i.e., making sure that the screen doesn't scroll when you normally press j / k, until the target element is completely not on the screen)

File: frontend/src/components/worksheets/Worksheet/Worksheet.js [hunk 3]
```diff
@@ -598,6 +598,33 @@ class Worksheet extends React.Component {
...
+        if (shouldScroll) {
+            const element = subIndex
+                ? $(`#codalab-worksheet-item-${index}-subitem-${subIndex}`)
+                : $(`#codalab-worksheet-item-${index}`);
+
+            function isOnScreen(element) {
+                if (element.offset() === undefined) return false;
+                var elementOffsetTop = element.offset().top;
+                // For result table which should first scroll itself when a row inside it is not visible anymore.
+                // The max height for the result table is 500.
```
Comment (epicfaace) [inline frontend/src/components/worksheets/Worksheet/Worksheet.js]: Is there a way to factor out "500" as a constant, so we can easily change it later without having to go through this code?

Comment (yipenghe) [reply frontend/src/components/worksheets/Worksheet/Worksheet.js]: I guess (<= 262 ||   >= 262 + MAX_TABLE_HEIGHT) would do (line 614 below)

File: frontend/src/components/worksheets/Worksheet/Worksheet.js (hunk 2 above)
Comment (yuqijin) [reply frontend/src/components/worksheets/Worksheet/Worksheet.js]: Have made the modification!

File: frontend/src/components/worksheets/Worksheet/Worksheet.js (hunk 1 above)
Comment (yuqijin) [reply frontend/src/components/worksheets/Worksheet/Worksheet.js]: Changed to `let`. Thanks!

**Review by epicfaace — APPROVED** [review]
