### PR TITLE
Fix Schema Deletion Bug

### LINKED ISSUE #3461: deleting schema on worksheet has some rough edges
Go to a worksheet and create a schema.  If it is selected and you hit backspace, it doesn't delete it and tries to delete bundles instead.

You have to open up the schema, and then click the trash can.  This works, but the message asks if you want to delete the markdown rather than deleting the schema.

### PR DESCRIPTION
**Pull request by yuqijin**
### Reasons for making this change

update schema deletion confirmation message;
enable to use the short key(`backspace`/`del`) to delete a schema

### Related issues

fixes #3461 
### Screenshots

ezgif com-gif-maker (4)

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [x] I've added and/or updated tests, if this is a backend change
* [x] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [x] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

File: frontend/src/components/worksheets/Worksheet/Worksheet.js [hunk 1]
```diff
@@ -397,10 +397,14 @@ class Worksheet extends React.Component {
             this.setState({ openedDialog: null, deleteItemCallback: null });
             return;
         }
-        if (cmd_type === 'deleteItem') {
```
Comment (epicfaace) [inline frontend/src/components/worksheets/Worksheet/Worksheet.js:400]: What was deleteItem used for earlier? Do we not need a handler for that case anymore?

Comment (yuqijin) [reply frontend/src/components/worksheets/Worksheet/Worksheet.js:400]: previously `deleteitem` refers to `deleteMarkdown` only. I think the naming is ambiguous since we now have `delete Schema` as well, so I rename it to be `deleteMarkdown` & `deleteSchema`

**Review by epicfaace — APPROVED** [review]
