### PR TITLE
Fix showing file contents for record item 

### LINKED ISSUE #2446: Record mode doesn't display the value in files
It is related to async file loading

To reproduce:
create a schema with a field using files:
% schema a
% add hello /stdout

display bundles in record mode
% display record a
[]{0x12312312}

### PR DESCRIPTION
**Pull request by yipenghe**
fix #2446 

to test:
create a schema with a field using files:
% schema a
% add hello /stdout

display bundles in record mode
% display record a

### CODE REVIEW

File: frontend/src/components/worksheets/items/RecordItem.js [hunk 1]
```diff
@@ -28,13 +30,6 @@ class RecordItem extends React.Component {
         this.setState({ bundleInfoUpdates: { ...bundleInfoUpdates, ...update } });
     };
 
-    shouldComponentUpdate(nextProps, nextState) {
-        return (
-            worksheetItemPropsChanged(this.props, nextProps) ||
```
Comment (yipenghe) [inline frontend/src/components/worksheets/items/RecordItem.js:33]: The worksheetItemPropsChanged check doesn't really make sense to me

**Review by epicfaace — APPROVED** [review]
