### PR TITLE
Fix problem that does not copy exclude-patterns when rerun a bundle

### LINKED ISSUE #3238: "exclude_patterns" is not copied over when rerunning a bundle
**Describe the bug**
`exclude_patterns` is not copied over when rerunning a bundle on the UI.

**To Reproduce**
Steps to reproduce the behavior :
1. Create a bundle and specify a value for `exclude_patterns`
2. Rerun the bundle from step 1
3. Notice that `exclude_patterns` is not specified for the new bundle

**Expected behavior**
I would expect the value of the field to get copied over.

### PR DESCRIPTION
**Pull request by wwwjn**
### Reasons for making this change
When rerun a bundle, the `exclude-patterns` parameter is not copied.

### Related issues

Fix #3238 

### Screenshots
test4

### Checklist

* [x] I've added a screenshot of the changes, if this is a frontend change
* [ ] I've added and/or updated tests, if this is a backend change
* [ ] I've run the [pre-commit.sh](https://github.com/codalab/codalab-worksheets/blob/master/pre-commit.sh) script
* [ ] I've updated [docs](https://github.com/codalab/codalab-worksheets/tree/master/docs), if needed

### CODE REVIEW

File: frontend/src/components/worksheets/NewRun/NewRun.jsx [hunk 1]
```diff
@@ -300,6 +301,14 @@ class NewRun extends React.Component<
 
         if (command) args.push(command);
 
+        // exclude_patterns a list of arguments, so put it at the end of commands
+        if (exclude_patterns) {
+            args.push(`--exclude-patterns`);
+            for (let i = 0; i < exclude_patterns.length; i++) {
```
Comment (epicfaace) [inline frontend/src/components/worksheets/NewRun/NewRun.jsx]: We can just replace this with

```
args.push(...exclude_patterns);
```

See https://stackoverflow.com/questions/1374126/how-to-extend-an-existing-javascript-array-with-another-array-without-creating

File: frontend/src/components/worksheets/NewRun/NewRun.jsx [hunk 2]
```diff
@@ -300,6 +301,14 @@ class NewRun extends React.Component<
 
         if (command) args.push(command);
 
+        // exclude_patterns a list of arguments, so put it at the end of commands
```
Comment (epicfaace) [inline frontend/src/components/worksheets/NewRun/NewRun.jsx]:
```suggestion
        // exclude_patterns can take a list of arguments, so put it at the end
```

**Review by epicfaace — APPROVED** [review]
